In [3]:
import pandas as pd
df=pd.read_csv("car_ownership.csv")
df.head(3)

   monthly_salary  owns_car
0           22000         0
1           25000         0
2           47000         1

In [4]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.linear_model import LogisticRegression
x=df[['monthly_salary']]
y=df['owns_car']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model=LogisticRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8888888888888888

In [18]:
x_test

    monthly_salary
8            62000
13           29000
9            61000
21           26000
0            22000
11           28000
16           25000
17           58000
12           27000

In [19]:
y_test.tolist()

[1, 0, 1, 0, 0, 0, 1, 1, 0]

In [20]:
model.predict(x_test)

array([1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [22]:
model.predict_proba(x_test)

array([[0.04530932, 0.95469068],
       [0.80955349, 0.19044651],
       [0.05158003, 0.94841997],
       [0.86480041, 0.13519959],
       [0.91687254, 0.08312746],
       [0.82967465, 0.17032535],
       [0.87995016, 0.12004984],
       [0.07564619, 0.92435381],
       [0.84806892, 0.15193108]])

In [23]:
model.coef_,model.intercept_

(array([[0.00013621]]), array([-5.39725076]))

In [25]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [31]:
def prediction_function(salary,model):
    z=model.coef_*salary+model.intercept_
    y=sigmoid(z[0][0])
    return y

In [32]:
prediction_function(62000,model)

0.954690678813166

In [33]:
prediction_function(29000,model)

0.1904465115158154